export const FETCH_CONFERENCES_SUCCESS = "FETCH_CONFERENCES_SUCCESS";
export const FETCH_CONFERENCES_REQUEST = "FETCH_CONFERENCES_REQUEST";
export const FETCH_CONFERENCES_FAILED = "FETCH_CONFERENCES_FAILED";

export const FETCH_ADD_CONFERENCES_SUCCESS = "FETCH_ADD_CONFERENCES_SUCCESS";
export const FETCH_ADD_CONFERENCES_REQUEST = "FETCH_ADD_CONFERENCES_REQUEST";
export const FETCH_ADD_CONFERENCES_FAILED = "FETCH_ADD_CONFERENCES_FAILED";

export const FETCH_REGISTRATION_SUCCESS = "FETCH_REGISTRATION_SUCCESS";
export const FETCH_REGISTRATION_REQUEST = "FETCH_REGISTRATION_REQUEST";
export const FETCH_REGISTRATION_FAILED = "FETCH_REGISTRATION_FAILED";

export const SET_NULL_REGISTRATION_STATUS_SUCCESS = "SET_NULL_REGISTRATION_STATUS_SUCCESS";
export const SET_NULL_REGISTRATION_STATUS_REQUEST = "SET_NULL_REGISTRATION_STATUS_REQUEST";
export const SET_NULL_REGISTRATION_STATUS_FAILED = "SET_NULL_REGISTRATION_STATUS_FAILED";

export const SET_NULL_AUTHORIZATION_STATUS_SUCCESS = "SET_NULL_AUTHORIZATION_STATUS_SUCCESS";
export const SET_NULL_AUTHORIZATION_STATUS_REQUEST = "SET_NULL_AUTHORIZATION_STATUS_REQUEST";
export const SET_NULL_AUTHORIZATION_STATUS_FAILED = "SET_NULL_AUTHORIZATION_STATUS_FAILED";

export const FETCH_AUTHORIZATION_SUCCESS = "FETCH_AUTHORIZATION_SUCCESS";
export const FETCH_AUTHORIZATION_REQUEST = "FETCH_AUTHORIZATION_REQUEST";
export const FETCH_AUTHORIZATION_FAILED = "FETCH_AUTHORIZATION_FAILED";


export const FETCH_CONFERENCES_SUCCESS_BY_ID = "FETCH_CONFERENCES_SUCCESS_BY_ID";
export const FETCH_CONFERENCES_REQUEST_BY_ID = "FETCH_CONFERENCES_REQUEST_BY_ID";
export const FETCH_CONFERENCES_FAILED_BY_ID = "FETCH_CONFERENCES_FAILED_BY_ID";

export const FETCH_CONFERENCES_SUCCESS_BY_SEARCH_FILTER = "FETCH_CONFERENCES_SUCCESS_BY_SEARCH_FILTER";
export const FETCH_CONFERENCES_REQUEST_BY_SEARCH_FILTER = "FETCH_CONFERENCES_REQUEST_BY_SEARCH_FILTER";
export const FETCH_CONFERENCES_FAILED_BY_SEARCH_FILTER = "FETCH_CONFERENCES_FAILED_BY_SEARCH_FILTER";

export const FETCH_CONFERENCES_SUCCESS_BY_CATEGORIES_FILTER = "FETCH_CONFERENCES_SUCCESS_BY_CATEGORIES_FILTER";
export const FETCH_CONFERENCES_REQUEST_BY_CATEGORIES_FILTER = "FETCH_CONFERENCES_REQUEST_BY_CATEGORIES_FILTER";
export const FETCH_CONFERENCES_FAILED_BY_CATEGORIES_FILTER = "FETCH_CONFERENCES_FAILED_BY_CATEGORIES_FILTER";

export const FETCH_APPLICATIONS_SUCCESS = "FETCH_APPLICATIONS_SUCCESS";
export const FETCH_APPLICATIONS_REQUEST = "FETCH_APPLICATIONS_REQUEST";
export const FETCH_APPLICATIONS_FAILED = "FETCH_APPLICATIONS_FAILED";

export const FETCH_CONFIRMED_APPLICATIONS_SUCCESS = "FETCH_CONFIRMED_APPLICATIONS_SUCCESS";
export const FETCH_CONFIRMED_APPLICATIONS_REQUEST = "FETCH_CONFIRMED_APPLICATIONS_REQUEST";
export const FETCH_CONFIRMED_APPLICATIONS_FAILED = "FETCH_CONFIRMED_APPLICATIONS_FAILED";

export const FETCH_CANCEL_APPLICATIONS_SUCCESS = "FETCH_CANCEL_APPLICATIONS_SUCCESS";
export const FETCH_CANCEL_APPLICATIONS_REQUEST = "FETCH_CANCEL_APPLICATIONS_REQUEST";
export const FETCH_CANCEL_APPLICATIONS_FAILED = "FETCH_CANCEL_APPLICATIONS_FAILED";

export const FETCH_ACCEPT_APPLICATIONS_SUCCESS = "FETCH_ACCEPT_APPLICATIONS_SUCCESS";
export const FETCH_ACCEPT_APPLICATIONS_REQUEST = "FETCH_ACCEPT_APPLICATIONS_REQUEST";
export const FETCH_ACCEPT_APPLICATIONS_FAILED = "FETCH_ACCEPT_APPLICATIONS_FAILED";

export const FETCH_SET_APPLICATIONS_SUCCESS = "FETCH_SET_APPLICATIONS_SUCCESS";
export const FETCH_SET_APPLICATIONS_REQUEST = "FETCH_SET_APPLICATIONS_REQUEST";
export const FETCH_SET_APPLICATIONS_FAILED = "FETCH_SET_APPLICATIONS_FAILED";

export const SET_NULL_APPLICATION_STATUS_SUCCESS = "SET_NULL_APPLICATION_STATUS_SUCCESS";
export const SET_NULL_APPLICATION_STATUS_REQUEST = "SET_NULL_APPLICATION_STATUS_REQUEST";
export const SET_NULL_APPLICATION_STATUS_FAILED = "SET_NULL_APPLICATION_STATUS_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const DELETE_APPLICATION_SUCCESS = "DELETE_APPLICATION_SUCCESS";
export const DELETE_APPLICATION_REQUEST = "DELETE_APPLICATION_REQUEST";
export const DELETE_APPLICATION_FAILED = "DELETE_APPLICATION_FAILED";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";





export const COLORS = {
    MERCURY:'#E9E9E9',
    EBONY_CLAY:'#21253c',
    REDICAL_RED:'#fe4661',
    EAST_BAY:'#414a78',
    SILVER:'#C7C7C7',
}
